/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedAwaitingApprovalRouteImport } from './routes/_authenticated/awaiting-approval'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicMediaRouteImport } from './routes/_public/media'
import { Route as PublicResourcesRouteImport } from './routes/_public/resources'
import { Route as PublicSongsRouteImport } from './routes/_public/songs'
import { Route as PublicTeamRouteImport } from './routes/_public/team'
import { Route as PublicWorshipRouteImport } from './routes/_public/worship'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardActivityRouteImport } from './routes/_authenticated/dashboard/activity'
import { Route as AuthenticatedDashboardMediaRouteImport } from './routes/_authenticated/dashboard/media'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardResourcesRouteImport } from './routes/_authenticated/dashboard/resources'
import { Route as AuthenticatedDashboardScheduleRouteImport } from './routes/_authenticated/dashboard/schedule'
import { Route as AuthenticatedDashboardServicesRouteImport } from './routes/_authenticated/dashboard/services'
import { Route as AuthenticatedDashboardSetlistsRouteImport } from './routes/_authenticated/dashboard/setlists'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardSongsRouteImport } from './routes/_authenticated/dashboard/songs'
import { Route as AuthenticatedDashboardTeamRouteImport } from './routes/_authenticated/dashboard/team'
import { Route as AuthenticatedDashboardTeam_newRouteImport } from './routes/_authenticated/dashboard/team_new'
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated/dashboard/users'
import { Route as PublicResourcesIdRouteImport } from './routes/_public/resources.$id'
import { Route as PublicSetlistsIndexRouteImport } from './routes/_public/setlists/index'
import { Route as PublicSetlistsIdRouteImport } from './routes/_public/setlists/$id'
import { Route as PublicSongsIndexRouteImport } from './routes/_public/songs/index'
import { Route as PublicSongsIdRouteImport } from './routes/_public/songs/$id'
import { Route as PublicTeamIdRouteImport } from './routes/_public/team.$id'
import { Route as AuthenticatedDashboardMediaNewRouteImport } from './routes/_authenticated/dashboard/media/new'
import { Route as AuthenticatedDashboardResourcesNewRouteImport } from './routes/_authenticated/dashboard/resources/new'
import { Route as AuthenticatedDashboardScheduleIdRouteImport } from './routes/_authenticated/dashboard/schedule/$id'
import { Route as AuthenticatedDashboardScheduleNewRouteImport } from './routes/_authenticated/dashboard/schedule/new'
import { Route as AuthenticatedDashboardServicesIdRouteImport } from './routes/_authenticated/dashboard/services/$id'
import { Route as AuthenticatedDashboardServicesNewRouteImport } from './routes/_authenticated/dashboard/services/new'
import { Route as AuthenticatedDashboardSetlistsIdRouteImport } from './routes/_authenticated/dashboard/setlists/$id'
import { Route as AuthenticatedDashboardSetlistsNewRouteImport } from './routes/_authenticated/dashboard/setlists/new'
import { Route as AuthenticatedDashboardSongsIndexRouteImport } from './routes/_authenticated/dashboard/songs/index'
import { Route as AuthenticatedDashboardSongsIdRouteImport } from './routes/_authenticated/dashboard/songs/$id'
import { Route as AuthenticatedDashboardSongsNewRouteImport } from './routes/_authenticated/dashboard/songs/new'
import { Route as AuthenticatedDashboardTeamIdRouteImport } from './routes/_authenticated/dashboard/team/$id'
import { Route as AuthenticatedDashboardUsersNewRouteImport } from './routes/_authenticated/dashboard/users/new'
import { Route as AuthenticatedDashboardTeamEditIdRouteImport } from './routes/_authenticated/dashboard/team/edit/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAwaitingApprovalRoute =
  AuthenticatedAwaitingApprovalRouteImport.update({
    id: '/awaiting-approval',
    path: '/awaiting-approval',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMediaRoute = PublicMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResourcesRoute = PublicResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSongsRoute = PublicSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTeamRoute = PublicTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWorshipRoute = PublicWorshipRouteImport.update({
  id: '/worship',
  path: '/worship',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardActivityRoute =
  AuthenticatedDashboardActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMediaRoute =
  AuthenticatedDashboardMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardResourcesRoute =
  AuthenticatedDashboardResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardScheduleRoute =
  AuthenticatedDashboardScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardServicesRoute =
  AuthenticatedDashboardServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSetlistsRoute =
  AuthenticatedDashboardSetlistsRouteImport.update({
    id: '/setlists',
    path: '/setlists',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSongsRoute =
  AuthenticatedDashboardSongsRouteImport.update({
    id: '/songs',
    path: '/songs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTeamRoute =
  AuthenticatedDashboardTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTeam_newRoute =
  AuthenticatedDashboardTeam_newRouteImport.update({
    id: '/team_new',
    path: '/team_new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsersRoute =
  AuthenticatedDashboardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const PublicResourcesIdRoute = PublicResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicResourcesRoute,
} as any)
const PublicSetlistsIndexRoute = PublicSetlistsIndexRouteImport.update({
  id: '/setlists/',
  path: '/setlists/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSetlistsIdRoute = PublicSetlistsIdRouteImport.update({
  id: '/setlists/$id',
  path: '/setlists/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSongsIndexRoute = PublicSongsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicSongsRoute,
} as any)
const PublicSongsIdRoute = PublicSongsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicSongsRoute,
} as any)
const PublicTeamIdRoute = PublicTeamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicTeamRoute,
} as any)
const AuthenticatedDashboardMediaNewRoute =
  AuthenticatedDashboardMediaNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardMediaRoute,
  } as any)
const AuthenticatedDashboardResourcesNewRoute =
  AuthenticatedDashboardResourcesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardResourcesRoute,
  } as any)
const AuthenticatedDashboardScheduleIdRoute =
  AuthenticatedDashboardScheduleIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardScheduleRoute,
  } as any)
const AuthenticatedDashboardScheduleNewRoute =
  AuthenticatedDashboardScheduleNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardScheduleRoute,
  } as any)
const AuthenticatedDashboardServicesIdRoute =
  AuthenticatedDashboardServicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardServicesRoute,
  } as any)
const AuthenticatedDashboardServicesNewRoute =
  AuthenticatedDashboardServicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardServicesRoute,
  } as any)
const AuthenticatedDashboardSetlistsIdRoute =
  AuthenticatedDashboardSetlistsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardSetlistsRoute,
  } as any)
const AuthenticatedDashboardSetlistsNewRoute =
  AuthenticatedDashboardSetlistsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardSetlistsRoute,
  } as any)
const AuthenticatedDashboardSongsIndexRoute =
  AuthenticatedDashboardSongsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardSongsRoute,
  } as any)
const AuthenticatedDashboardSongsIdRoute =
  AuthenticatedDashboardSongsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardSongsRoute,
  } as any)
const AuthenticatedDashboardSongsNewRoute =
  AuthenticatedDashboardSongsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardSongsRoute,
  } as any)
const AuthenticatedDashboardTeamIdRoute =
  AuthenticatedDashboardTeamIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardTeamRoute,
  } as any)
const AuthenticatedDashboardUsersNewRoute =
  AuthenticatedDashboardUsersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardUsersRoute,
  } as any)
const AuthenticatedDashboardTeamEditIdRoute =
  AuthenticatedDashboardTeamEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedDashboardTeamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awaiting-approval': typeof AuthenticatedAwaitingApprovalRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/login': typeof PublicLoginRoute
  '/media': typeof PublicMediaRoute
  '/resources': typeof PublicResourcesRouteWithChildren
  '/songs': typeof PublicSongsRouteWithChildren
  '/team': typeof PublicTeamRouteWithChildren
  '/worship': typeof PublicWorshipRoute
  '/dashboard/activity': typeof AuthenticatedDashboardActivityRoute
  '/dashboard/media': typeof AuthenticatedDashboardMediaRouteWithChildren
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/resources': typeof AuthenticatedDashboardResourcesRouteWithChildren
  '/dashboard/schedule': typeof AuthenticatedDashboardScheduleRouteWithChildren
  '/dashboard/services': typeof AuthenticatedDashboardServicesRouteWithChildren
  '/dashboard/setlists': typeof AuthenticatedDashboardSetlistsRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/songs': typeof AuthenticatedDashboardSongsRouteWithChildren
  '/dashboard/team': typeof AuthenticatedDashboardTeamRouteWithChildren
  '/dashboard/team_new': typeof AuthenticatedDashboardTeam_newRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRouteWithChildren
  '/resources/$id': typeof PublicResourcesIdRoute
  '/setlists/$id': typeof PublicSetlistsIdRoute
  '/songs/$id': typeof PublicSongsIdRoute
  '/team/$id': typeof PublicTeamIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/setlists/': typeof PublicSetlistsIndexRoute
  '/songs/': typeof PublicSongsIndexRoute
  '/dashboard/media/new': typeof AuthenticatedDashboardMediaNewRoute
  '/dashboard/resources/new': typeof AuthenticatedDashboardResourcesNewRoute
  '/dashboard/schedule/$id': typeof AuthenticatedDashboardScheduleIdRoute
  '/dashboard/schedule/new': typeof AuthenticatedDashboardScheduleNewRoute
  '/dashboard/services/$id': typeof AuthenticatedDashboardServicesIdRoute
  '/dashboard/services/new': typeof AuthenticatedDashboardServicesNewRoute
  '/dashboard/setlists/$id': typeof AuthenticatedDashboardSetlistsIdRoute
  '/dashboard/setlists/new': typeof AuthenticatedDashboardSetlistsNewRoute
  '/dashboard/songs/$id': typeof AuthenticatedDashboardSongsIdRoute
  '/dashboard/songs/new': typeof AuthenticatedDashboardSongsNewRoute
  '/dashboard/team/$id': typeof AuthenticatedDashboardTeamIdRoute
  '/dashboard/users/new': typeof AuthenticatedDashboardUsersNewRoute
  '/dashboard/songs/': typeof AuthenticatedDashboardSongsIndexRoute
  '/dashboard/team/edit/$id': typeof AuthenticatedDashboardTeamEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awaiting-approval': typeof AuthenticatedAwaitingApprovalRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/login': typeof PublicLoginRoute
  '/media': typeof PublicMediaRoute
  '/resources': typeof PublicResourcesRouteWithChildren
  '/team': typeof PublicTeamRouteWithChildren
  '/worship': typeof PublicWorshipRoute
  '/dashboard/activity': typeof AuthenticatedDashboardActivityRoute
  '/dashboard/media': typeof AuthenticatedDashboardMediaRouteWithChildren
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/resources': typeof AuthenticatedDashboardResourcesRouteWithChildren
  '/dashboard/schedule': typeof AuthenticatedDashboardScheduleRouteWithChildren
  '/dashboard/services': typeof AuthenticatedDashboardServicesRouteWithChildren
  '/dashboard/setlists': typeof AuthenticatedDashboardSetlistsRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/team': typeof AuthenticatedDashboardTeamRouteWithChildren
  '/dashboard/team_new': typeof AuthenticatedDashboardTeam_newRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRouteWithChildren
  '/resources/$id': typeof PublicResourcesIdRoute
  '/setlists/$id': typeof PublicSetlistsIdRoute
  '/songs/$id': typeof PublicSongsIdRoute
  '/team/$id': typeof PublicTeamIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/setlists': typeof PublicSetlistsIndexRoute
  '/songs': typeof PublicSongsIndexRoute
  '/dashboard/media/new': typeof AuthenticatedDashboardMediaNewRoute
  '/dashboard/resources/new': typeof AuthenticatedDashboardResourcesNewRoute
  '/dashboard/schedule/$id': typeof AuthenticatedDashboardScheduleIdRoute
  '/dashboard/schedule/new': typeof AuthenticatedDashboardScheduleNewRoute
  '/dashboard/services/$id': typeof AuthenticatedDashboardServicesIdRoute
  '/dashboard/services/new': typeof AuthenticatedDashboardServicesNewRoute
  '/dashboard/setlists/$id': typeof AuthenticatedDashboardSetlistsIdRoute
  '/dashboard/setlists/new': typeof AuthenticatedDashboardSetlistsNewRoute
  '/dashboard/songs/$id': typeof AuthenticatedDashboardSongsIdRoute
  '/dashboard/songs/new': typeof AuthenticatedDashboardSongsNewRoute
  '/dashboard/team/$id': typeof AuthenticatedDashboardTeamIdRoute
  '/dashboard/users/new': typeof AuthenticatedDashboardUsersNewRoute
  '/dashboard/songs': typeof AuthenticatedDashboardSongsIndexRoute
  '/dashboard/team/edit/$id': typeof AuthenticatedDashboardTeamEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/awaiting-approval': typeof AuthenticatedAwaitingApprovalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/media': typeof PublicMediaRoute
  '/_public/resources': typeof PublicResourcesRouteWithChildren
  '/_public/songs': typeof PublicSongsRouteWithChildren
  '/_public/team': typeof PublicTeamRouteWithChildren
  '/_public/worship': typeof PublicWorshipRoute
  '/_authenticated/dashboard/activity': typeof AuthenticatedDashboardActivityRoute
  '/_authenticated/dashboard/media': typeof AuthenticatedDashboardMediaRouteWithChildren
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/resources': typeof AuthenticatedDashboardResourcesRouteWithChildren
  '/_authenticated/dashboard/schedule': typeof AuthenticatedDashboardScheduleRouteWithChildren
  '/_authenticated/dashboard/services': typeof AuthenticatedDashboardServicesRouteWithChildren
  '/_authenticated/dashboard/setlists': typeof AuthenticatedDashboardSetlistsRouteWithChildren
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/songs': typeof AuthenticatedDashboardSongsRouteWithChildren
  '/_authenticated/dashboard/team': typeof AuthenticatedDashboardTeamRouteWithChildren
  '/_authenticated/dashboard/team_new': typeof AuthenticatedDashboardTeam_newRoute
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersRouteWithChildren
  '/_public/resources/$id': typeof PublicResourcesIdRoute
  '/_public/setlists/$id': typeof PublicSetlistsIdRoute
  '/_public/songs/$id': typeof PublicSongsIdRoute
  '/_public/team/$id': typeof PublicTeamIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_public/setlists/': typeof PublicSetlistsIndexRoute
  '/_public/songs/': typeof PublicSongsIndexRoute
  '/_authenticated/dashboard/media/new': typeof AuthenticatedDashboardMediaNewRoute
  '/_authenticated/dashboard/resources/new': typeof AuthenticatedDashboardResourcesNewRoute
  '/_authenticated/dashboard/schedule/$id': typeof AuthenticatedDashboardScheduleIdRoute
  '/_authenticated/dashboard/schedule/new': typeof AuthenticatedDashboardScheduleNewRoute
  '/_authenticated/dashboard/services/$id': typeof AuthenticatedDashboardServicesIdRoute
  '/_authenticated/dashboard/services/new': typeof AuthenticatedDashboardServicesNewRoute
  '/_authenticated/dashboard/setlists/$id': typeof AuthenticatedDashboardSetlistsIdRoute
  '/_authenticated/dashboard/setlists/new': typeof AuthenticatedDashboardSetlistsNewRoute
  '/_authenticated/dashboard/songs/$id': typeof AuthenticatedDashboardSongsIdRoute
  '/_authenticated/dashboard/songs/new': typeof AuthenticatedDashboardSongsNewRoute
  '/_authenticated/dashboard/team/$id': typeof AuthenticatedDashboardTeamIdRoute
  '/_authenticated/dashboard/users/new': typeof AuthenticatedDashboardUsersNewRoute
  '/_authenticated/dashboard/songs/': typeof AuthenticatedDashboardSongsIndexRoute
  '/_authenticated/dashboard/team/edit/$id': typeof AuthenticatedDashboardTeamEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awaiting-approval'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/login'
    | '/media'
    | '/resources'
    | '/songs'
    | '/team'
    | '/worship'
    | '/dashboard/activity'
    | '/dashboard/media'
    | '/dashboard/profile'
    | '/dashboard/resources'
    | '/dashboard/schedule'
    | '/dashboard/services'
    | '/dashboard/setlists'
    | '/dashboard/settings'
    | '/dashboard/songs'
    | '/dashboard/team'
    | '/dashboard/team_new'
    | '/dashboard/users'
    | '/resources/$id'
    | '/setlists/$id'
    | '/songs/$id'
    | '/team/$id'
    | '/dashboard/'
    | '/setlists/'
    | '/songs/'
    | '/dashboard/media/new'
    | '/dashboard/resources/new'
    | '/dashboard/schedule/$id'
    | '/dashboard/schedule/new'
    | '/dashboard/services/$id'
    | '/dashboard/services/new'
    | '/dashboard/setlists/$id'
    | '/dashboard/setlists/new'
    | '/dashboard/songs/$id'
    | '/dashboard/songs/new'
    | '/dashboard/team/$id'
    | '/dashboard/users/new'
    | '/dashboard/songs/'
    | '/dashboard/team/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awaiting-approval'
    | '/about'
    | '/contact'
    | '/login'
    | '/media'
    | '/resources'
    | '/team'
    | '/worship'
    | '/dashboard/activity'
    | '/dashboard/media'
    | '/dashboard/profile'
    | '/dashboard/resources'
    | '/dashboard/schedule'
    | '/dashboard/services'
    | '/dashboard/setlists'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/team_new'
    | '/dashboard/users'
    | '/resources/$id'
    | '/setlists/$id'
    | '/songs/$id'
    | '/team/$id'
    | '/dashboard'
    | '/setlists'
    | '/songs'
    | '/dashboard/media/new'
    | '/dashboard/resources/new'
    | '/dashboard/schedule/$id'
    | '/dashboard/schedule/new'
    | '/dashboard/services/$id'
    | '/dashboard/services/new'
    | '/dashboard/setlists/$id'
    | '/dashboard/setlists/new'
    | '/dashboard/songs/$id'
    | '/dashboard/songs/new'
    | '/dashboard/team/$id'
    | '/dashboard/users/new'
    | '/dashboard/songs'
    | '/dashboard/team/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/awaiting-approval'
    | '/_authenticated/dashboard'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/login'
    | '/_public/media'
    | '/_public/resources'
    | '/_public/songs'
    | '/_public/team'
    | '/_public/worship'
    | '/_authenticated/dashboard/activity'
    | '/_authenticated/dashboard/media'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/resources'
    | '/_authenticated/dashboard/schedule'
    | '/_authenticated/dashboard/services'
    | '/_authenticated/dashboard/setlists'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/songs'
    | '/_authenticated/dashboard/team'
    | '/_authenticated/dashboard/team_new'
    | '/_authenticated/dashboard/users'
    | '/_public/resources/$id'
    | '/_public/setlists/$id'
    | '/_public/songs/$id'
    | '/_public/team/$id'
    | '/_authenticated/dashboard/'
    | '/_public/setlists/'
    | '/_public/songs/'
    | '/_authenticated/dashboard/media/new'
    | '/_authenticated/dashboard/resources/new'
    | '/_authenticated/dashboard/schedule/$id'
    | '/_authenticated/dashboard/schedule/new'
    | '/_authenticated/dashboard/services/$id'
    | '/_authenticated/dashboard/services/new'
    | '/_authenticated/dashboard/setlists/$id'
    | '/_authenticated/dashboard/setlists/new'
    | '/_authenticated/dashboard/songs/$id'
    | '/_authenticated/dashboard/songs/new'
    | '/_authenticated/dashboard/team/$id'
    | '/_authenticated/dashboard/users/new'
    | '/_authenticated/dashboard/songs/'
    | '/_authenticated/dashboard/team/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/awaiting-approval': {
      id: '/_authenticated/awaiting-approval'
      path: '/awaiting-approval'
      fullPath: '/awaiting-approval'
      preLoaderRoute: typeof AuthenticatedAwaitingApprovalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/media': {
      id: '/_public/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof PublicMediaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/resources': {
      id: '/_public/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof PublicResourcesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/songs': {
      id: '/_public/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof PublicSongsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/team': {
      id: '/_public/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof PublicTeamRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/worship': {
      id: '/_public/worship'
      path: '/worship'
      fullPath: '/worship'
      preLoaderRoute: typeof PublicWorshipRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/activity': {
      id: '/_authenticated/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof AuthenticatedDashboardActivityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/media': {
      id: '/_authenticated/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof AuthenticatedDashboardMediaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/resources': {
      id: '/_authenticated/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof AuthenticatedDashboardResourcesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/schedule': {
      id: '/_authenticated/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof AuthenticatedDashboardScheduleRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/services': {
      id: '/_authenticated/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof AuthenticatedDashboardServicesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/setlists': {
      id: '/_authenticated/dashboard/setlists'
      path: '/setlists'
      fullPath: '/dashboard/setlists'
      preLoaderRoute: typeof AuthenticatedDashboardSetlistsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/songs': {
      id: '/_authenticated/dashboard/songs'
      path: '/songs'
      fullPath: '/dashboard/songs'
      preLoaderRoute: typeof AuthenticatedDashboardSongsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/team': {
      id: '/_authenticated/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof AuthenticatedDashboardTeamRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/team_new': {
      id: '/_authenticated/dashboard/team_new'
      path: '/team_new'
      fullPath: '/dashboard/team_new'
      preLoaderRoute: typeof AuthenticatedDashboardTeam_newRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_public/resources/$id': {
      id: '/_public/resources/$id'
      path: '/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof PublicResourcesIdRouteImport
      parentRoute: typeof PublicResourcesRoute
    }
    '/_public/setlists/': {
      id: '/_public/setlists/'
      path: '/setlists'
      fullPath: '/setlists/'
      preLoaderRoute: typeof PublicSetlistsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/setlists/$id': {
      id: '/_public/setlists/$id'
      path: '/setlists/$id'
      fullPath: '/setlists/$id'
      preLoaderRoute: typeof PublicSetlistsIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/songs/': {
      id: '/_public/songs/'
      path: '/'
      fullPath: '/songs/'
      preLoaderRoute: typeof PublicSongsIndexRouteImport
      parentRoute: typeof PublicSongsRoute
    }
    '/_public/songs/$id': {
      id: '/_public/songs/$id'
      path: '/$id'
      fullPath: '/songs/$id'
      preLoaderRoute: typeof PublicSongsIdRouteImport
      parentRoute: typeof PublicSongsRoute
    }
    '/_public/team/$id': {
      id: '/_public/team/$id'
      path: '/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof PublicTeamIdRouteImport
      parentRoute: typeof PublicTeamRoute
    }
    '/_authenticated/dashboard/media/new': {
      id: '/_authenticated/dashboard/media/new'
      path: '/new'
      fullPath: '/dashboard/media/new'
      preLoaderRoute: typeof AuthenticatedDashboardMediaNewRouteImport
      parentRoute: typeof AuthenticatedDashboardMediaRoute
    }
    '/_authenticated/dashboard/resources/new': {
      id: '/_authenticated/dashboard/resources/new'
      path: '/new'
      fullPath: '/dashboard/resources/new'
      preLoaderRoute: typeof AuthenticatedDashboardResourcesNewRouteImport
      parentRoute: typeof AuthenticatedDashboardResourcesRoute
    }
    '/_authenticated/dashboard/schedule/$id': {
      id: '/_authenticated/dashboard/schedule/$id'
      path: '/$id'
      fullPath: '/dashboard/schedule/$id'
      preLoaderRoute: typeof AuthenticatedDashboardScheduleIdRouteImport
      parentRoute: typeof AuthenticatedDashboardScheduleRoute
    }
    '/_authenticated/dashboard/schedule/new': {
      id: '/_authenticated/dashboard/schedule/new'
      path: '/new'
      fullPath: '/dashboard/schedule/new'
      preLoaderRoute: typeof AuthenticatedDashboardScheduleNewRouteImport
      parentRoute: typeof AuthenticatedDashboardScheduleRoute
    }
    '/_authenticated/dashboard/services/$id': {
      id: '/_authenticated/dashboard/services/$id'
      path: '/$id'
      fullPath: '/dashboard/services/$id'
      preLoaderRoute: typeof AuthenticatedDashboardServicesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardServicesRoute
    }
    '/_authenticated/dashboard/services/new': {
      id: '/_authenticated/dashboard/services/new'
      path: '/new'
      fullPath: '/dashboard/services/new'
      preLoaderRoute: typeof AuthenticatedDashboardServicesNewRouteImport
      parentRoute: typeof AuthenticatedDashboardServicesRoute
    }
    '/_authenticated/dashboard/setlists/$id': {
      id: '/_authenticated/dashboard/setlists/$id'
      path: '/$id'
      fullPath: '/dashboard/setlists/$id'
      preLoaderRoute: typeof AuthenticatedDashboardSetlistsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardSetlistsRoute
    }
    '/_authenticated/dashboard/setlists/new': {
      id: '/_authenticated/dashboard/setlists/new'
      path: '/new'
      fullPath: '/dashboard/setlists/new'
      preLoaderRoute: typeof AuthenticatedDashboardSetlistsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardSetlistsRoute
    }
    '/_authenticated/dashboard/songs/': {
      id: '/_authenticated/dashboard/songs/'
      path: '/'
      fullPath: '/dashboard/songs/'
      preLoaderRoute: typeof AuthenticatedDashboardSongsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardSongsRoute
    }
    '/_authenticated/dashboard/songs/$id': {
      id: '/_authenticated/dashboard/songs/$id'
      path: '/$id'
      fullPath: '/dashboard/songs/$id'
      preLoaderRoute: typeof AuthenticatedDashboardSongsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardSongsRoute
    }
    '/_authenticated/dashboard/songs/new': {
      id: '/_authenticated/dashboard/songs/new'
      path: '/new'
      fullPath: '/dashboard/songs/new'
      preLoaderRoute: typeof AuthenticatedDashboardSongsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardSongsRoute
    }
    '/_authenticated/dashboard/team/$id': {
      id: '/_authenticated/dashboard/team/$id'
      path: '/$id'
      fullPath: '/dashboard/team/$id'
      preLoaderRoute: typeof AuthenticatedDashboardTeamIdRouteImport
      parentRoute: typeof AuthenticatedDashboardTeamRoute
    }
    '/_authenticated/dashboard/users/new': {
      id: '/_authenticated/dashboard/users/new'
      path: '/new'
      fullPath: '/dashboard/users/new'
      preLoaderRoute: typeof AuthenticatedDashboardUsersNewRouteImport
      parentRoute: typeof AuthenticatedDashboardUsersRoute
    }
    '/_authenticated/dashboard/team/edit/$id': {
      id: '/_authenticated/dashboard/team/edit/$id'
      path: '/edit/$id'
      fullPath: '/dashboard/team/edit/$id'
      preLoaderRoute: typeof AuthenticatedDashboardTeamEditIdRouteImport
      parentRoute: typeof AuthenticatedDashboardTeamRoute
    }
  }
}

interface AuthenticatedDashboardMediaRouteChildren {
  AuthenticatedDashboardMediaNewRoute: typeof AuthenticatedDashboardMediaNewRoute
}

const AuthenticatedDashboardMediaRouteChildren: AuthenticatedDashboardMediaRouteChildren =
  {
    AuthenticatedDashboardMediaNewRoute: AuthenticatedDashboardMediaNewRoute,
  }

const AuthenticatedDashboardMediaRouteWithChildren =
  AuthenticatedDashboardMediaRoute._addFileChildren(
    AuthenticatedDashboardMediaRouteChildren,
  )

interface AuthenticatedDashboardResourcesRouteChildren {
  AuthenticatedDashboardResourcesNewRoute: typeof AuthenticatedDashboardResourcesNewRoute
}

const AuthenticatedDashboardResourcesRouteChildren: AuthenticatedDashboardResourcesRouteChildren =
  {
    AuthenticatedDashboardResourcesNewRoute:
      AuthenticatedDashboardResourcesNewRoute,
  }

const AuthenticatedDashboardResourcesRouteWithChildren =
  AuthenticatedDashboardResourcesRoute._addFileChildren(
    AuthenticatedDashboardResourcesRouteChildren,
  )

interface AuthenticatedDashboardScheduleRouteChildren {
  AuthenticatedDashboardScheduleIdRoute: typeof AuthenticatedDashboardScheduleIdRoute
  AuthenticatedDashboardScheduleNewRoute: typeof AuthenticatedDashboardScheduleNewRoute
}

const AuthenticatedDashboardScheduleRouteChildren: AuthenticatedDashboardScheduleRouteChildren =
  {
    AuthenticatedDashboardScheduleIdRoute:
      AuthenticatedDashboardScheduleIdRoute,
    AuthenticatedDashboardScheduleNewRoute:
      AuthenticatedDashboardScheduleNewRoute,
  }

const AuthenticatedDashboardScheduleRouteWithChildren =
  AuthenticatedDashboardScheduleRoute._addFileChildren(
    AuthenticatedDashboardScheduleRouteChildren,
  )

interface AuthenticatedDashboardServicesRouteChildren {
  AuthenticatedDashboardServicesIdRoute: typeof AuthenticatedDashboardServicesIdRoute
  AuthenticatedDashboardServicesNewRoute: typeof AuthenticatedDashboardServicesNewRoute
}

const AuthenticatedDashboardServicesRouteChildren: AuthenticatedDashboardServicesRouteChildren =
  {
    AuthenticatedDashboardServicesIdRoute:
      AuthenticatedDashboardServicesIdRoute,
    AuthenticatedDashboardServicesNewRoute:
      AuthenticatedDashboardServicesNewRoute,
  }

const AuthenticatedDashboardServicesRouteWithChildren =
  AuthenticatedDashboardServicesRoute._addFileChildren(
    AuthenticatedDashboardServicesRouteChildren,
  )

interface AuthenticatedDashboardSetlistsRouteChildren {
  AuthenticatedDashboardSetlistsIdRoute: typeof AuthenticatedDashboardSetlistsIdRoute
  AuthenticatedDashboardSetlistsNewRoute: typeof AuthenticatedDashboardSetlistsNewRoute
}

const AuthenticatedDashboardSetlistsRouteChildren: AuthenticatedDashboardSetlistsRouteChildren =
  {
    AuthenticatedDashboardSetlistsIdRoute:
      AuthenticatedDashboardSetlistsIdRoute,
    AuthenticatedDashboardSetlistsNewRoute:
      AuthenticatedDashboardSetlistsNewRoute,
  }

const AuthenticatedDashboardSetlistsRouteWithChildren =
  AuthenticatedDashboardSetlistsRoute._addFileChildren(
    AuthenticatedDashboardSetlistsRouteChildren,
  )

interface AuthenticatedDashboardSongsRouteChildren {
  AuthenticatedDashboardSongsIdRoute: typeof AuthenticatedDashboardSongsIdRoute
  AuthenticatedDashboardSongsNewRoute: typeof AuthenticatedDashboardSongsNewRoute
  AuthenticatedDashboardSongsIndexRoute: typeof AuthenticatedDashboardSongsIndexRoute
}

const AuthenticatedDashboardSongsRouteChildren: AuthenticatedDashboardSongsRouteChildren =
  {
    AuthenticatedDashboardSongsIdRoute: AuthenticatedDashboardSongsIdRoute,
    AuthenticatedDashboardSongsNewRoute: AuthenticatedDashboardSongsNewRoute,
    AuthenticatedDashboardSongsIndexRoute:
      AuthenticatedDashboardSongsIndexRoute,
  }

const AuthenticatedDashboardSongsRouteWithChildren =
  AuthenticatedDashboardSongsRoute._addFileChildren(
    AuthenticatedDashboardSongsRouteChildren,
  )

interface AuthenticatedDashboardTeamRouteChildren {
  AuthenticatedDashboardTeamIdRoute: typeof AuthenticatedDashboardTeamIdRoute
  AuthenticatedDashboardTeamEditIdRoute: typeof AuthenticatedDashboardTeamEditIdRoute
}

const AuthenticatedDashboardTeamRouteChildren: AuthenticatedDashboardTeamRouteChildren =
  {
    AuthenticatedDashboardTeamIdRoute: AuthenticatedDashboardTeamIdRoute,
    AuthenticatedDashboardTeamEditIdRoute:
      AuthenticatedDashboardTeamEditIdRoute,
  }

const AuthenticatedDashboardTeamRouteWithChildren =
  AuthenticatedDashboardTeamRoute._addFileChildren(
    AuthenticatedDashboardTeamRouteChildren,
  )

interface AuthenticatedDashboardUsersRouteChildren {
  AuthenticatedDashboardUsersNewRoute: typeof AuthenticatedDashboardUsersNewRoute
}

const AuthenticatedDashboardUsersRouteChildren: AuthenticatedDashboardUsersRouteChildren =
  {
    AuthenticatedDashboardUsersNewRoute: AuthenticatedDashboardUsersNewRoute,
  }

const AuthenticatedDashboardUsersRouteWithChildren =
  AuthenticatedDashboardUsersRoute._addFileChildren(
    AuthenticatedDashboardUsersRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardActivityRoute: typeof AuthenticatedDashboardActivityRoute
  AuthenticatedDashboardMediaRoute: typeof AuthenticatedDashboardMediaRouteWithChildren
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardResourcesRoute: typeof AuthenticatedDashboardResourcesRouteWithChildren
  AuthenticatedDashboardScheduleRoute: typeof AuthenticatedDashboardScheduleRouteWithChildren
  AuthenticatedDashboardServicesRoute: typeof AuthenticatedDashboardServicesRouteWithChildren
  AuthenticatedDashboardSetlistsRoute: typeof AuthenticatedDashboardSetlistsRouteWithChildren
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSongsRoute: typeof AuthenticatedDashboardSongsRouteWithChildren
  AuthenticatedDashboardTeamRoute: typeof AuthenticatedDashboardTeamRouteWithChildren
  AuthenticatedDashboardTeam_newRoute: typeof AuthenticatedDashboardTeam_newRoute
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardActivityRoute: AuthenticatedDashboardActivityRoute,
    AuthenticatedDashboardMediaRoute:
      AuthenticatedDashboardMediaRouteWithChildren,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardResourcesRoute:
      AuthenticatedDashboardResourcesRouteWithChildren,
    AuthenticatedDashboardScheduleRoute:
      AuthenticatedDashboardScheduleRouteWithChildren,
    AuthenticatedDashboardServicesRoute:
      AuthenticatedDashboardServicesRouteWithChildren,
    AuthenticatedDashboardSetlistsRoute:
      AuthenticatedDashboardSetlistsRouteWithChildren,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSongsRoute:
      AuthenticatedDashboardSongsRouteWithChildren,
    AuthenticatedDashboardTeamRoute:
      AuthenticatedDashboardTeamRouteWithChildren,
    AuthenticatedDashboardTeam_newRoute: AuthenticatedDashboardTeam_newRoute,
    AuthenticatedDashboardUsersRoute:
      AuthenticatedDashboardUsersRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAwaitingApprovalRoute: typeof AuthenticatedAwaitingApprovalRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAwaitingApprovalRoute: AuthenticatedAwaitingApprovalRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicResourcesRouteChildren {
  PublicResourcesIdRoute: typeof PublicResourcesIdRoute
}

const PublicResourcesRouteChildren: PublicResourcesRouteChildren = {
  PublicResourcesIdRoute: PublicResourcesIdRoute,
}

const PublicResourcesRouteWithChildren = PublicResourcesRoute._addFileChildren(
  PublicResourcesRouteChildren,
)

interface PublicSongsRouteChildren {
  PublicSongsIdRoute: typeof PublicSongsIdRoute
  PublicSongsIndexRoute: typeof PublicSongsIndexRoute
}

const PublicSongsRouteChildren: PublicSongsRouteChildren = {
  PublicSongsIdRoute: PublicSongsIdRoute,
  PublicSongsIndexRoute: PublicSongsIndexRoute,
}

const PublicSongsRouteWithChildren = PublicSongsRoute._addFileChildren(
  PublicSongsRouteChildren,
)

interface PublicTeamRouteChildren {
  PublicTeamIdRoute: typeof PublicTeamIdRoute
}

const PublicTeamRouteChildren: PublicTeamRouteChildren = {
  PublicTeamIdRoute: PublicTeamIdRoute,
}

const PublicTeamRouteWithChildren = PublicTeamRoute._addFileChildren(
  PublicTeamRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicMediaRoute: typeof PublicMediaRoute
  PublicResourcesRoute: typeof PublicResourcesRouteWithChildren
  PublicSongsRoute: typeof PublicSongsRouteWithChildren
  PublicTeamRoute: typeof PublicTeamRouteWithChildren
  PublicWorshipRoute: typeof PublicWorshipRoute
  PublicSetlistsIdRoute: typeof PublicSetlistsIdRoute
  PublicSetlistsIndexRoute: typeof PublicSetlistsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicMediaRoute: PublicMediaRoute,
  PublicResourcesRoute: PublicResourcesRouteWithChildren,
  PublicSongsRoute: PublicSongsRouteWithChildren,
  PublicTeamRoute: PublicTeamRouteWithChildren,
  PublicWorshipRoute: PublicWorshipRoute,
  PublicSetlistsIdRoute: PublicSetlistsIdRoute,
  PublicSetlistsIndexRoute: PublicSetlistsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
